# When updating config file, run `tmux source ~/.tmux.conf`

# Installs Tmux Plugin manager
set -g @plugin 'tmux-plugins/tpm'
# Install tmux ressurrect to bring all sessions back after resturt
set -g @plugin 'tmux-plugins/tmux-resurrect'
# Installs and enables saving state of tmux sessions every 15 min
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
# Install vim-tmux-navigator. It already comes with presets for hjkl and different mode navigation
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enabled mouse
set -g mouse on
# don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane 

# Enabled vim keys in tmux
setw -g mode-keys vi
# Enable wl-copy to yank from tmux
bind -T copy-mode-vi v send -X begin-selection
# Disable autoscroll down after copy by removing -and-cancel
bind -T copy-mode-vi y send -X copy-pipe "wl-copy"

# moves the current window one position to the left in the tab bar, and follows it
bind-key -r < swap-window -t -1\; select-window -t -1
bind-key -r > swap-window -t +1\; select-window -t +1

# Bind S-C to open a new pane with 30% width and launches Claude Code
# -c "#{pane_current_path}" sets the working directory to the current pane's directory, then "claude" runs it in the new pane.
# -h - vertical split (side by side)
bind C split-window -h -l 30% -c "#{pane_current_path}" "claude"

run '~/.tmux/plugins/tpm/tpm'
